spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD:${DB_PASS}}

    hikari:
      pool-name: TicketLedgerHiPool
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        generate_statistics: false

logging:
  level:
    root: INFO
    com.ticketledger: INFO
    org.hibernate: WARN

security:
  jwt:
    secret-key: ${JWT_SECRET:${JWT_SECRET_KEY}}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}


booking:
  lock-duration-minutes: 15
  default-base-price: 10.00
  currency: INR
  cleanup-interval-ms: 60000

ticketledger:
  payment:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY}
      admin-alert-email: ${ADMIN_ALERT_EMAIL}
