spring:
  threads:
    virtual:
      enabled: true
  application:
    name: TicketLedger
  
  main:
    banner-mode: "off"

  # ACTIVATION
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"

  # JPA & FLYWAY (Common)
  jpa:
    open-in-view: false               # CRITICAL: Keep false to prevent N+1 issues in View layer 
    generate-ddl: false               # We use Flyway
    hibernate:
      ddl-auto: none              # Flyway handles schema migrations
    properties:
      hibernate:
      
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: "classpath:db/migration"

admin:
  system-user-id: "00000000-0000-0000-0000-000000000000"
  reconciliation:
    threshold-seconds: 60
    max-batch-size: 50

logging:
  pattern:
    # Use 'console' to define the full log line format
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([${spring.application.name:ticket-ledger},%X{traceId:-},%X{spanId:-}]){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
