package com.ticketledger.domain.repository;

import java.util.Optional;
import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.ticketledger.domain.entity.User;

@Repository
public interface UserRepository extends JpaRepository<User, UUID> {

    /**
     *  Method to find a user by email.
     */
    Optional<User> findByEmail(String email);

    /**
     * Method to check if an email is already registered.
     * efficient count-based check generated by Hibernate.
     */
    boolean existsByEmail(String email);
}